# Generated by scripts/sync-config.py
PAYNODE_ROUTER_ADDRESS = "0x4A73696ccF76E7381b044cB95127B3784369Ed63"
PAYNODE_ROUTER_ADDRESS_SANDBOX = "0x24cD8b68aaC209217ff5a6ef1Bf55a59f2c8Ca6F"
BASE_USDC_ADDRESS = "0x833589fCD6eDb6E08f4c7C32D4f71b54bdA02913"
BASE_USDC_ADDRESS_SANDBOX = "0x109AEddD656Ed2761d1e210E179329105039c784"
BASE_USDC_DECIMALS = 6

PROTOCOL_TREASURY = "0x598bF63F5449876efafa7b36b77Deb2070621C0E"
PROTOCOL_FEE_BPS = 100
MIN_PAYMENT_AMOUNT = 1000

BASE_RPC_URLS = ["https://mainnet.base.org", "https://base.meowrpc.com", "https://1rpc.io/base"]
BASE_RPC_URLS_SANDBOX = ["https://sepolia.base.org", "https://base-sepolia-rpc.publicnode.com"]

ACCEPTED_TOKENS = {
    8453: ["0x833589fCD6eDb6E08f4c7C32D4f71b54bdA02913"],
    84532: ["0x109AEddD656Ed2761d1e210E179329105039c784"]
}

PAYNODE_ROUTER_ABI = [
    {
        "anonymous": False,
        "inputs": [
            {"indexed": True, "name": "orderId", "type": "bytes32"},
            {"indexed": True, "name": "merchant", "type": "address"},
            {"indexed": True, "name": "payer", "type": "address"},
            {"indexed": False, "name": "token", "type": "address"},
            {"indexed": False, "name": "amount", "type": "uint256"},
            {"indexed": False, "name": "fee", "type": "uint256"},
            {"indexed": False, "name": "chainId", "type": "uint256"}
        ],
        "name": "PaymentReceived",
        "type": "event"
    }
]
