# Generated by scripts/sync-config.py
from enum import Enum
from typing import Any, Optional

class ErrorCode(str, Enum):
    rpc_error = 'rpc_error'
    insufficient_funds = 'insufficient_funds'
    amount_too_low = 'amount_too_low'
    token_not_accepted = 'token_not_accepted'
    transaction_failed = 'transaction_failed'
    duplicate_transaction = 'duplicate_transaction'
    invalid_receipt = 'invalid_receipt'
    internal_error = 'internal_error'
    transaction_not_found = 'transaction_not_found'
    wrong_contract = 'wrong_contract'
    order_mismatch = 'order_mismatch'
    missing_receipt = 'missing_receipt'

ERROR_MESSAGES = {
    ErrorCode.rpc_error: "Failed to connect to any provided RPC nodes.",
    ErrorCode.insufficient_funds: "Wallet lacks USDC or ETH for gas.",
    ErrorCode.amount_too_low: "Payment amount is below the protocol minimum (1000).",
    ErrorCode.token_not_accepted: "The provided token address is not in the whitelist.",
    ErrorCode.transaction_failed: "On-chain transaction reverted or failed.",
    ErrorCode.duplicate_transaction: "This transaction hash has already been consumed.",
    ErrorCode.invalid_receipt: "The provided receipt (TxHash) is malformed or invalid.",
    ErrorCode.internal_error: "An unexpected error occurred.",
    ErrorCode.transaction_not_found: "Transaction not found on-chain.",
    ErrorCode.wrong_contract: "Payment event was not emitted by the official PayNode contract.",
    ErrorCode.order_mismatch: "OrderId in receipt does not match requested ID.",
    ErrorCode.missing_receipt: "Please pay to PayNode contract and provide 'PAYMENT-SIGNATURE' header.",
}

class PayNodeException(Exception):
    def __init__(self, code: ErrorCode, message: Optional[str] = None, details: Optional[Any] = None):
        self.code = code
        self.message = message or ERROR_MESSAGES.get(code, "An unexpected error occurred.")
        self.details = details
        super().__init__(self.message)
